#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'DrugSchedulerMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 5

# The Active Message type associated with this message.
AM_TYPE = 13

class DrugSchedulerMsg(tinyos.message.Message.Message):
    # Create a new DrugSchedulerMsg of size 5.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=5):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <DrugSchedulerMsg> \n"
        try:
            s += "  [time_interval=0x%x]\n" % (self.get_time_interval())
        except:
            pass
        try:
            s += "  [amount=0x%x]\n" % (self.get_amount())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: time_interval
    #   Field type: long
    #   Offset (bits): 0
    #   Size (bits): 32
    #

    #
    # Return whether the field 'time_interval' is signed (False).
    #
    def isSigned_time_interval(self):
        return False
    
    #
    # Return whether the field 'time_interval' is an array (False).
    #
    def isArray_time_interval(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'time_interval'
    #
    def offset_time_interval(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'time_interval'
    #
    def offsetBits_time_interval(self):
        return 0
    
    #
    # Return the value (as a long) of the field 'time_interval'
    #
    def get_time_interval(self):
        return self.getUIntElement(self.offsetBits_time_interval(), 32, 1)
    
    #
    # Set the value of the field 'time_interval'
    #
    def set_time_interval(self, value):
        self.setUIntElement(self.offsetBits_time_interval(), 32, value, 1)
    
    #
    # Return the size, in bytes, of the field 'time_interval'
    #
    def size_time_interval(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'time_interval'
    #
    def sizeBits_time_interval(self):
        return 32
    
    #
    # Accessor methods for field: amount
    #   Field type: short
    #   Offset (bits): 32
    #   Size (bits): 8
    #

    #
    # Return whether the field 'amount' is signed (False).
    #
    def isSigned_amount(self):
        return False
    
    #
    # Return whether the field 'amount' is an array (False).
    #
    def isArray_amount(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'amount'
    #
    def offset_amount(self):
        return (32 / 8)
    
    #
    # Return the offset (in bits) of the field 'amount'
    #
    def offsetBits_amount(self):
        return 32
    
    #
    # Return the value (as a short) of the field 'amount'
    #
    def get_amount(self):
        return self.getUIntElement(self.offsetBits_amount(), 8, 1)
    
    #
    # Set the value of the field 'amount'
    #
    def set_amount(self, value):
        self.setUIntElement(self.offsetBits_amount(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'amount'
    #
    def size_amount(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'amount'
    #
    def sizeBits_amount(self):
        return 8
    
