 #
 # This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 # This class includes values of some nesC constants from
 # Inclinometer.h.
 #/

class Constants:
    NORMALIZATION = 16383

